# .rubocop.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

RSpec/BeforeAfterAll:
  Enabled: false
Lint/Void: # new in 1.1
  Enabled: false
Metrics/AbcSize: # new in 1.0
  Enabled: false
Metrics/MethodLength: # new in 1.0
  Enabled: false
Metrics/PerceivedComplexity: # new in 1.0
  Enabled: false
Style/FormatStringToken: # new in 1.1
  Enabled: false
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: single_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
RSpec/ExampleLength:
  Enabled: true
  Max: 10
