# .rubocop.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7

Metrics/ModuleLength:
  Exclude:
    - "spec/**/*"

Naming/FileName:
  Exclude:
    - lib/uri-redis.rb
    - lib/uri-valkey.rb

RSpec/BeforeAfterAll:
  Enabled: false
Lint/Void: # new in 1.1
  Enabled: false
Metrics/AbcSize: # new in 1.0
  Enabled: false
Metrics/MethodLength: # new in 1.0
  Enabled: false
Metrics/PerceivedComplexity: # new in 1.0
  Enabled: false
Style/FormatStringToken: # new in 1.1
  Enabled: false
Style/StringLiterals:
  EnforcedStyle: single_quotes
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/FrozenStringLiteralComment:
  Enabled: false
Layout/LineLength:
  Max: 120
RSpec/ExampleLength:
  Max: 10
